name: FactionsMongo
version: ${project.version}
main: io.github.lukeeey.factionsmongodb.FactionsMongoPlugin
author: lukeeey
loadbefore: [Factions]
api-version: 1.13
description: Adds MongoDB storage to the FactionsUUID plugin
commands:
  factionsmongo:
    aliases: [fmongo]
    usage: /fmongo <reload/import/help>
permissions:
  fmongo.*:
    default: false
    children:
      fmongo.reload:
        default: op
      fmongo.import:
        default: op
      fmongo.export:
        default: op